### ISSUE TITLE
there is "+" missing in dwl file 

### ISSUE THREAD

**Issue by goo-bhim** [mulesoft-catalyst/metrics-toolkit#107]
this causes to miss API Manager API's which are more than 100. 

dwl file location : master/src/main/resources/dw/anypoint/save-aggregated-api-payload-var.dwl

**Comment by damiancalabresi** [comment]
Thanks! We'll look at the issue and validate it.

**Comment by panizzag** [comment]
Hi @goo-bhim. Thanks for collaborating!
The issue was confirmed and It will be fixed in the next releases. Cheers!

**Comment by panizzag** [comment]
Unit tests after the change:
![image](https://user-images.githubusercontent.com/50634447/133463782-38a3b903-2749-4a8d-9d3b-16a3d6eda4c3.png)

apiManagerMetrics is populated as expected (used an account with # assets > default offset to force the path):
![image](https://user-images.githubusercontent.com/50634447/133464147-2d4ebed0-74f5-4714-bb5e-057d75366146.png)

**Comment by richardmckinley** [comment]
Issue has been addressed in patch 1.8.1
