### ISSUE TITLE
Getting Error while running metrics accelerator 

### ISSUE THREAD

**Issue by amitkrjha1** [mulesoft-catalyst/metrics-toolkit#126]
apma

1) HTTP POST on resource 'https://anypoint.mulesoft.com:443/analytics/1.0/{{orgId}}/environments/{{envId}}/query' failed: bad request (400).

osv2

1) HTTP GET on resource 'https://object-store-stats.anypoint.mulesoft.com:443/api/v1/organizations/{{orgId}}/environments/{{envId}}' failed: too many requests (429).
2) HTTP GET on resource 'https://object-store-stats.anypoint.mulesoft.com:443/api/v1/organizations/{{orgId}}/environments/{{envId}}' failed: forbidden (403).

amq

1) HTTP GET on resource 'https://anypoint.mulesoft.com:443/mq/admin/api/v1/organizations/{{orgId}}/environments/{{envId}}/regions/ca-central-1/destinations' failed: forbidden (403).

1. The query that Metrics framework uses to retrieve total transactions from API Manager Analytics API is not stable.
The API in question is - https://anypoint.mulesoft.com:443/analytics/1.0/{{orgId}}/environments/{{envId}}/query

It returns expected data sometimes and at other times it returns errors.
It is an important KPI to track. Can we please look at replacing this API call with an alternative call to get the same information or fixing the error?

2. The forbidden error is coming after all permissions mentioned in our documentation is added - 
```
Anypoint Platform user with the Organization Administrator role in the master organization and CloudHub Admin role (or specific permissions - see connected app section) in all environments of all Sub Orgs you want to collect data
```
 Can we please include specific permission associated with different collectors? For most of them the connected app does a good job of breakdown. However, AMQ and OSV2 seem to be missing.

**Comment by richardmckinley** [comment]
The issue regarding the analytics API being unstable should be fixed by adding a header Accept="application/json"
This fix is in the current develop branch and will form part of and upcoming release 

We were unable to replicate the 403 issues you report - to replicate I created a new user, granted the user Org Admin permissions in each Business Group, then executed a metrics lookup for AMQ and Object Store. No 403s occurred. 

If you are certain you have granted Org Admin permissions in each BG and still see 403 please reach out and we can investigate. 

Note you will see 403 for Runtime Manager related requests if you do not provide CloudHub Admin access. 


For the Too Many Requests - this is a limit enforced by the platform API and so not within our control.

**Comment by amitkrjha1** [comment]
Hi Richard,

About 403 issue - As per the documentation -

   - Anypoint Platform user with the Organization Administrator role in the
   master organization and CloudHub Admin role (or specific permissions - see
   connected app section) in all environments of all Sub Orgs you want to
   collect data


So I am reading it as Org Admin is required only in Master Org and CloudHub
Admin is required in all environments of Sub Orgs and Master Org if any
environments exist in Master Org.
If we need to provide user with an Org Admin role in each Sub Orgs as well
then in my opinion we should update the documentation.

Regards,
<http://www.mulesoft.com/>
Amit Jha, Senior Solutions Architect

1095 Avenue of the Americas, 6th Ave,
New York, NY 10036

M +1 646.906.4995 <555.555.5555>

<https://www.linkedin.com/company/mulesoft>   <https://twitter.com/mulesoft>
   <https://www.facebook.com/MuleSoft>   <https://videos.mulesoft.com/> We're
hiring! <http://www.mulesoft.com/careers>

**Comment by richardmckinley** [comment]
Hi Amit, 
Thanks for the feedback! Re-reading the docs with this in mind I can see how it could be read as you described. 
I will update the docs to be more explicit. 
Richard

**Comment by richardmckinley** [comment]
Documentation has been updated. 
Release 1.8.0 contained a patch to fix analytics API call issue
