### ISSUE TITLE
Dashboards fail to pass Splunk Clouds App Inspect

### ISSUE THREAD

**Issue by jrehm-mmm** [mulesoft-catalyst/metrics-toolkit#133]
When trying to upload a custom app to Splunk Cloud, the dashaboards fail to pass App Inspect

**The following Error is found and will stop the user from installing**
Change the version attribute in the root node of your Simple XML dashboard default/data/ui/views/runtime_manager__rtf__sandbox.xml to `<form version=1.1>`. Earlier dashboard versions introduce security vulnerabilities into your apps and are not permitted in Splunk Cloud File: default/data/ui/views/runtime_manager__rtf__sandbox.xml

**Comment by richardmckinley** [comment]
Hi @jrehm-mmm 
I have been unable to replicate this. I have just created the dashboards in Splunk Cloud by directly copying the provided xml into the dashboard source and did not receive any such errors. I am going to mark the issue as closed. 
If you want to provide additional information on how to replicate please feel free to re-open. 
Thanks and regards, 
Richard

**Comment by jrehm-mmm** [comment]
The way you are testing will not fail. The failure will come if you try to package up the app and try to install it on Splunk Cloud.  It will fail app inspect.

If you expect that users are going to manually create the dashboards then it's not a concern.

**Comment by richardmckinley** [comment]
Thanks @jrehm-mmm for your quick reply, and for providing that extra detail. 
Yes, the dashboards are provided as standalone examples, not as a package-able app so the expectation is that users will install these manually. The dashboards are intended to be examples only, with the expectation that users will refine, extend and customise these to meet their specific requirements. 
I will mark this item as closed, and thanks again for your feedback. 
Richard
