### ISSUE TITLE
Plaintext passwords are incorrectly decoded as base64

### ISSUE THREAD

**Issue by richardmckinley** [mulesoft-catalyst/metrics-toolkit#137]
Passwords provided in plaintext which contain groups of 4 characters are considered "valid base64" and so are decoded to nonsense values. This is causing authentication against platform APIs to fail when plaintext passwords matching the pattern are provided 
![image](https://user-images.githubusercontent.com/58299919/134504058-06c41b6a-0a48-4ef1-a4c5-22208f0c0e44.png)

**Comment by richardmckinley** [comment]
Solution has been identified and implemented. Updates are required to the embedded dashboards before the new version can be released

**Comment by domagalat** [comment]
Hello,
This change still not working. I have retrieved metrics-toolkit 1.8.2. release from this localization https://github.com/mulesoft-catalyst/metrics-toolkit/releases/tag/1.8.2 from this source code 
![1](https://user-images.githubusercontent.com/27124540/135107724-9c689cd3-4479-4fbc-a0c2-e75cd9fda9c3.png)
I have tested this on my trial and company account and the result is the same.
![2](https://user-images.githubusercontent.com/27124540/135107956-605c22ef-bb10-46f7-abcd-cc915b8d1299.png)

**Comment by richardmckinley** [comment]
Hi @domagalat 
Can you confirm whether you are passing the new header X-PLAINTEXT-PASSWORD = true when passing a plain text password? 
The new logic uses is as follows: 
```var clientSecret = attributes.headers."x-anypnt-client-secret"
var password = attributes.headers."x-anypnt-password"
fun isBase64(text) = text matches(/^([A-Za-z0-9+]{4})*([A-Za-z0-9+]{3}=|[A-Za-z0-9+]{2}==)?$/)
fun getSecret(secret) = if (isBase64(secret default ""))
		fromBase64(secret) as String 
	else secret
---
if (!isEmpty(clientSecret))
	clientSecret
else 
	getSecret(password)

**Comment by domagalat** [comment]
No I'm passing this header X-ANYPNT-PASSWORD in Postman and this header X-ANYPNT-PASSWORD when I'm using console
![3](https://user-images.githubusercontent.com/27124540/135122517-715e46ae-00ef-40c4-823e-055621f75e79.png)
.

**Comment by richardmckinley** [comment]
@domagalat and is the value you provide base64 encoded? 
If you want to provide a plain text password in the header you need to also pass X-PLAINTEXT-PASSWORD=true
![image](https://user-images.githubusercontent.com/58299919/135123146-3c02b30f-846a-4f54-95c3-e21a006ed95b.png)
Otherwise, you need to basse64 encode your password
![image](https://user-images.githubusercontent.com/58299919/135123417-99200054-4aa9-4b2f-ac97-395dcad61e12.png)

**Comment by domagalat** [comment]
Ok, I didn't know that. Let me try

**Comment by richardmckinley** [comment]
No worries. Hopefully that resolves it, and this has been a useful exercise to highlight that we need to add some additional information to the documentation 
Thanks

**Comment by domagalat** [comment]
Ok authentication is working fine now, but I'm facing a lot of issues regarding errors 502 etc. below is an example of such errors like these in the attached errors.txt file.
[errors.txt](https://github.com/mulesoft-catalyst/metrics-toolkit/files/7245909/errors.txt)
Could you help here?

**Comment by richardmckinley** [comment]
@domagalat as the password issue is resolved I'm going to close this issue. 

I don't seem to get any 502 errors when testing the application. Please double check you haven't modified any other configurations, you're using the correct Anypoint host URL for your account, and the user/connected app you are using has access to all of the required roles, business groups and permissions. 
If you think there is a bug, please feel free to open another issue so we can track it separately for better visibility. 
Thanks and regards, 
Richard
