### ISSUE TITLE
Error when deploying the latest version (Release 1.8.2)

### ISSUE THREAD

**Issue by jorge-aravena** [mulesoft-catalyst/metrics-toolkit#157]
Deployment failure:

`Error: Failed to deploy artifact [metrics-accelerator]. ConfigurationException: [aggregators/aggregator-platform-benefits-metrics.xml:12]: A static value ('payload.access_token') was given for parameter 'targetValue' but it requires an expression" }
`

This is fixed by going to the mentioned XML and in line 12 replace:

`targetValue="payload.access_token"`

with:

`targetValue="#[payload.access_token]"`

**Comment by jorge-aravena** [comment]
Same thing with file: 

`aggregators/aggregator-platform-metrics.xml:18`

**Comment by richardmckinley** [comment]
HI @jorge-aravena 
Thanks for raising this and for sharing your solution! 

We were aware of the behaviour when migrating to Mule 4.4.x and implemented the exact same fix as you. This has been pushed to the develop branch in #150 but has not been released to master yet. 

Thanks again for raising, 
Richard
