### ISSUE TITLE
Beginner Don't Know how to Run

### ISSUE THREAD

**Issue by GoBenGoh** [mulesoft-catalyst/metrics-toolkit#159]
Hi, I'm looking at the readme and it says to run the project after changing properties. What properties am I supposed to change and why isn't there an option to run it in Anypoint Studio? Do I need to change something in the .project file?  When I try the Run As command, there are no options to run the project.

**Comment by GoBenGoh** [comment]
I downloaded and tried running from Anypoint Studio. There is no standard run configuration as shown here, meaning I can't run it. Shown here:
![image](https://user-images.githubusercontent.com/76719511/142793643-014e2206-6332-416a-b849-7c43f76954dc.png)

**Comment by richardmckinley** [comment]
HI @GoBenGoh, 
The tool assumes a level of MuleSoft knowledge and therefore we can't walk beginners through foundational steps. However, if you follow this [tutorial](http://workshop.tools.mulesoft.com/modules/module3_lab3) it should give you enough basic knowledge. 
If you need support in defining a training program I suggest speaking to your CSM as they will be able to recommend the relevant modules to support you and your team. 
Richard
