### ISSUE TITLE
How to access Metrics Toolkit Web UI via DLB expects "/api" in mapping rule output path

### ISSUE THREAD

**Issue by stackmerge** [mulesoft-catalyst/metrics-toolkit#162]
Team,
We are trying to use this project in our Anypoint Platform to send platform metrics to Anypoint Monitoring and use Web UI also. We have deployed this mule app behind DLB in cloudhub and tried accessing "Metrics Toolkit UI" via DLB expects "/api" in mapping rule output path but we failed to access web UI due to DLB mapping rules. 

Note: We can not change our DLB mapping rules since these are in use for a long time by multiple deployments. Please see attached screenshots for more details.

Please let us know any workaround/solution for this issue(accessing web UI via DLB expects "/api" in mapping rule output path).

![1](https://user-images.githubusercontent.com/68315630/143985093-17f6b36f-49a6-4e67-bd5a-8fe230bf2f69.PNG)
![2](https://user-images.githubusercontent.com/68315630/143985098-94bc2c1b-0336-4d8e-9de2-70749b32520e.PNG)

**Comment by richardmckinley** [comment]
Hi @stackmerge, 
We cannot provide guidance on how to configure your DLB mappings etc. You can always change the path for the embedded dashboard HTTP listener as required to work with your existing DLB config. For example, `path: "/api/dashboard/*"`
Hope that helps, 
Richard
