### ISSUE TITLE
Runtime 4.4.0 Deploy Failure aggregator-platform-benefits-metrics.xml

### ISSUE THREAD

**Issue by GoBenGoh** [mulesoft-catalyst/metrics-toolkit#164]
When running the toolkit on runtime 4.4.0, I get an error at line 12 of aggregators/aggregator-platform-benefits-metrics.xml:12: "A static value ('payload.access_token') was given for parameter 'targetValue' but it requires an expression." I have not changed anything in that xml file. Running the toolkit on 4.3.0 seems to work but I feel like the toolkit should be able to run on 4.4.0.

![image](https://user-images.githubusercontent.com/76719511/145121585-6c731559-0edc-4da6-a10a-50ccaae76d99.png)

**Comment by richardmckinley** [comment]
Hi @GoBenGoh, 
Please see #157
