### ISSUE TITLE
2 MUnit error tests keep failing (branch 4.4.0)

### ISSUE THREAD

**Issue by GoBenGoh** [mulesoft-catalyst/metrics-toolkit#166]
Only two tests are failing, preventing me from deploying to Cloudhub:

- get-sdlc-metrics-errors-test in unit-test-aggregator-sdlc-metrics-errors.xml
- unit-test-aggregator-platform-metrics-errors-test in unit-test-aggregator-platform-metrics-errors.xml

Seems like the only difference between the expected and actual outputs is a single "\r\". Does anyone have any idea how to fix this?

These are their respective failure messages:

`java.lang.AssertionError: The response payload is not the expected at file: [unit-test-aggregator-sdlc-metrics-errors.xml], line: [86]
Expected: "Exception(s) were found for route(s): \n\t0: org.mule.runtime.core.internal.processor.interceptor.InterceptionException: \n\t1: org.mule.runtime.core.internal.processor.interceptor.InterceptionException: "
     but: "Exception(s) were found for route(s): \r\n\t0: org.mule.runtime.core.internal.processor.interceptor.InterceptionException: \r\n\t1: org.mule.runtime.core.internal.processor.interceptor.InterceptionException: " at (root).sdlcMetrics.errors[3][0]
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)`

`java.lang.AssertionError: The response payload is not the expected at file: [unit-test-aggregator-platform-metrics-errors.xml], line: [319]
Expected: "Exception(s) were found for route(s): \r\n\t0: org.mule.runtime.core.internal.processor.interceptor.InterceptionException: \r\n\t1: org.mule.runtime.core.internal.processor.interceptor.InterceptionException: \r\n\t2: org.mule.runtime.core.internal.processor.interceptor.InterceptionException: \r\n\t3: org.mule.runtime.core.internal.processor.interceptor.InterceptionException: ","Exception(s) were found for route(s): \r\n\t0: org.mule.runtime.core.api.retry.policy.RetryPolicyExhaustedException: 'until-successful' retries exhausted. Last exception message was: \r\n\t1: org.mule.runtime.core.api.retry.policy.RetryPolicyExhaustedException: 'until-successful' retries exhausted. Last exception message was: \r\n\t2: org.mule.runtime.core.api.retry.policy.RetryPolicyExhaustedException: 'until-successful' retries exhausted. Last exception message was: \r\n\t3: org.mule.runtime.core.api.retry.policy.RetryPolicyExhaustedException: 'until-successful' retries exhausted. Last exception message was: ","Exception(s) were found for route(s): \r\n\t0: org.mule.runtime.core.internal.processor.interceptor.InterceptionException: \r\n\t1: org.mule.runtime.core.internal.processor.interceptor.InterceptionException: \r\n\t2: org.mule.runtime.core.internal.processor.interceptor.InterceptionException: \r\n\t3: org.mule.runtime.core.internal.processor.interceptor.InterceptionException: ","Exception(s) were found for route(s): \r\n\t0: org.mule.runtime.core.internal.processor.interceptor.InterceptionException: \r\n\t1: org.mule.runtime.core.internal.processor.interceptor.InterceptionException: \r\n\t2: org.mule.runtime.core.internal.processor.interceptor.InterceptionException: \r\n\t3: org.mule.runtime.core.internal.processor.interceptor.InterceptionException: ","Exception(s) were found for route(s): \r\n\t0: org.mule.runtime.core.internal.processor.interceptor.InterceptionException: \r\n\t1: org.mule.runtime.core.internal.processor.interceptor.InterceptionException: \r\n\t2: org.mule.runtime.core.internal.processor.interceptor.InterceptionException: \r\n\t3: org.mule.runtime.core.internal.processor.interceptor.InterceptionException: ","Exception(s) were found for route(s): \r\n\t0: org.mule.runtime.core.internal.processor.interceptor.InterceptionException: \r\n\t1: org.mule.runtime.core.internal.processor.interceptor.InterceptionException: \r\n\t2: org.mule.runtime.core.internal.processor.interceptor.InterceptionException: \r\n\t3: org.mule.runtime.core.internal.processor.interceptor.InterceptionException: ","Exception(s) were found for route(s): \r\n\t0: org.mule.runtime.core.internal.processor.interceptor.InterceptionException: \r\n\t1: org.mule.runtime.core.internal.processor.interceptor.InterceptionException: \r\n\t2: org.mule.runtime.core.internal.processor.interceptor.InterceptionException: \r\n\t3: org.mule.runtime.core.internal.processor.interceptor.InterceptionException: ","Exception(s) were found for route(s): \r\n\t0: org.mule.runtime.core.internal.processor.interceptor.InterceptionException: \r\n\t1: org.mule.runtime.core.internal.processor.interceptor.InterceptionException: \r\n\t2: org.mule.runtime.core.internal.processor.interceptor.InterceptionException: \r\n\t3: org.mule.runtime.core.internal.processor.interceptor.InterceptionException: ","'until-successful' retries exhausted. Last exception message was: ","Exception(s) were found for route(s): \r\n\t0: org.mule.runtime.core.internal.processor.interceptor.InterceptionException: \r\n\t1: org.mule.runtime.core.internal.processor.interceptor.InterceptionException: \r\n\t2: org.mule.runtime.core.internal.processor.interceptor.InterceptionException: \r\n\t3: org.mule.runtime.core.internal.processor.interceptor.InterceptionException: "
     but: "Exception(s) were found for route(s): \n\t0: org.mule.runtime.core.internal.processor.interceptor.InterceptionException: \n\t1: org.mule.runtime.core.internal.processor.interceptor.InterceptionException: \n\t2: org.mule.runtime.core.internal.processor.interceptor.InterceptionException: \n\t3: org.mule.runtime.core.internal.processor.interceptor.InterceptionException: " at (root)[0].errors[8][0],"Exception(s) were found for route(s): \n\t0: org.mule.runtime.core.api.retry.policy.RetryPolicyExhaustedException: 'until-successful' retries exhausted\n\t1: org.mule.runtime.core.api.retry.policy.RetryPolicyExhaustedException: 'until-successful' retries exhausted\n\t2: org.mule.runtime.core.api.retry.policy.RetryPolicyExhaustedException: 'until-successful' retries exhausted\n\t3: org.mule.runtime.core.api.retry.policy.RetryPolicyExhaustedException: 'until-successful' retries exhausted" at (root)[0].errors[7][0],"Exception(s) were found for route(s): \n\t0: org.mule.runtime.core.internal.processor.interceptor.InterceptionException: \n\t1: org.mule.runtime.core.internal.processor.interceptor.InterceptionException: \n\t2: org.mule.runtime.core.internal.processor.interceptor.InterceptionException: \n\t3: org.mule.runtime.core.internal.processor.interceptor.InterceptionException: " at (root)[0].errors[5][3][0],"Exception(s) were found for route(s): \n\t0: org.mule.runtime.core.internal.processor.interceptor.InterceptionException: \n\t1: org.mule.runtime.core.internal.processor.interceptor.InterceptionException: \n\t2: org.mule.runtime.core.internal.processor.interceptor.InterceptionException: \n\t3: org.mule.runtime.core.internal.processor.interceptor.InterceptionException: " at (root)[0].errors[5][2][0],"Exception(s) were found for route(s): \n\t0: org.mule.runtime.core.internal.processor.interceptor.InterceptionException: \n\t1: org.mule.runtime.core.internal.processor.interceptor.InterceptionException: \n\t2: org.mule.runtime.core.internal.processor.interceptor.InterceptionException: \n\t3: org.mule.runtime.core.internal.processor.interceptor.InterceptionException: " at (root)[0].errors[5][1][0],"Exception(s) were found for route(s): \n\t0: org.mule.runtime.core.internal.processor.interceptor.InterceptionException: \n\t1: org.mule.runtime.core.internal.processor.interceptor.InterceptionException: \n\t2: org.mule.runtime.core.internal.processor.interceptor.InterceptionException: \n\t3: org.mule.runtime.core.internal.processor.interceptor.InterceptionException: " at (root)[0].errors[5][0],"Exception(s) were found for route(s): \n\t0: org.mule.runtime.core.internal.processor.interceptor.InterceptionException: \n\t1: org.mule.runtime.core.internal.processor.interceptor.InterceptionException: \n\t2: org.mule.runtime.core.internal.processor.interceptor.InterceptionException: \n\t3: org.mule.runtime.core.internal.processor.interceptor.InterceptionException: " at (root)[0].errors[2][2][0],"Exception(s) were found for route(s): \n\t0: org.mule.runtime.core.internal.processor.interceptor.InterceptionException: \n\t1: org.mule.runtime.core.internal.processor.interceptor.InterceptionException: \n\t2: org.mule.runtime.core.internal.processor.interceptor.InterceptionException: \n\t3: org.mule.runtime.core.internal.processor.interceptor.InterceptionException: " at (root)[0].errors[2][0],"" at (root)[0].errors[1][0],"Exception(s) were found for route(s): \n\t0: org.mule.runtime.core.internal.processor.interceptor.InterceptionException: \n\t1: org.mule.runtime.core.internal.processor.interceptor.InterceptionException: \n\t2: org.mule.runtime.core.internal.processor.interceptor.InterceptionException: \n\t3: org.mule.runtime.core.internal.processor.interceptor.InterceptionException: " at (root)[0].errors[0]
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)`

**Comment by richardmckinley** [comment]
Hi @GoBenGoh 
\r is a carriage return used by Windows - see this StackOverflow [question](https://stackoverflow.com/questions/9260126/what-are-the-differences-between-char-literals-n-and-r-in-java)

**Comment by GoBenGoh** [comment]
Ah I see. I just skipped the test and now everything seems to work.
