### ISSUE TITLE
Incorrect date formatting causes MQ stats retrieval to fail

### ISSUE THREAD

**Issue by MartijnvdB** [mulesoft-catalyst/metrics-toolkit#169]
This is related to release 1.8.2, commit [e62ec39](https://github.com/mulesoft-catalyst/metrics-toolkit/commit/e62ec39dcb8ee9c015c29a2156a01fe88381d4c0), running on EE 4.3.0/4.4.0. 

In the file _api-call-mq.xml_, in the private flow _api-call-mq-queue-stats-flow_, the query parameters for the HTTP requests are calculated/formatted as follows:

```
startDate: (now() - |P1D|) as String {format: "E, dd MMM YYYY HH:mm:ss z"},
endDate: now() as String {format: "E, dd MMM YYYY HH:mm:ss z"}
```

This can cause the year to be formatted incorrectly. What happens is that _now() - |P1D|_ correctly calculates the _startDate_, and then the formatting string subtracts a whole year from that.

For example, running the above on _3 Jan 2022, 16:00:00 CET_ would result in a formatted string of _Sun, 02 Jan 2021 16:00:00 CET_. 

The result is that way too many calculated metrics points are requested, which causes the MQ API to return a 400 'Bad Request'.

**Solution**: replace 'YYYY' with 'uuuu'.

The use of the 'Y' and 'u' formatting strings is documented [here](https://docs.mulesoft.com/dataweave/2.4/dataweave-cookbook-format-dates).

**Comment by richardmckinley** [comment]
Hi @MartijnvdB 
Thank you very much for raising this issue and for your suggested solution. I have now implemented this in a number of date to string transformations to hopefully prevent any similar parsing issues. 
Richard

**Comment by MartijnvdB** [comment]
Hi @richardmckinley , thanks for the rapid fix and for your work on this toolkit :)
