### ISSUE TITLE
CH network metrics do not display 'Used' number

### ISSUE THREAD

**Issue by MartijnvdB** [mulesoft-catalyst/metrics-toolkit#182]
In metrics-toolkit v1.8.2 with CloudHub, the 'Used' metric graphs for VPC/VPN/LB/static IPs in the Splunk dashboard are always empty even though we have a number of each of them allocated. The 'Available' numbers are correct. 

When I examine the data in Splunk, I see that the values for the 'used' fields are always null.

![hc_1026](https://user-images.githubusercontent.com/16452270/160365768-54b0cced-9f3c-4d9a-b438-9c0bcbc7ec3d.png)

![hc_1025](https://user-images.githubusercontent.com/16452270/160347878-b6ec7ee0-98bb-42fd-ac1e-70b5febde323.png)

Splunk data:

![hc_1029](https://user-images.githubusercontent.com/16452270/160370752-bbbc01cf-b07f-4631-8945-6fa3afa15d6b.png)

The relevant output of the 'GET Platform Metrics' request in the Postman collection looks like this, the value in the fields vpcsUsed/vpnsUsed/dlbsUsed/staticIPsUsed are null.

![hc_1028](https://user-images.githubusercontent.com/16452270/160368974-7090ac5e-2419-47e5-bfda-49faef53b20d.png)

I ran the code in Anypoint Studio and captured the value of _vars.entitlement_ and _vars.usage_ which are used in the DW 'Build Metrics Aggregated Response' in _aggregator-platform-metrics.xml_. This shows that the fields 'vpcsConsumed' (vpn-, etc.) do not exist in those variables, hence they cannot be mapped.

We are using an Anypoint account, not a connected app, to access the Anypoint APIs.

**Comment by richardmckinley** [comment]
Hi @MartijnvdB 

Thanks for raising this. The first solution I would suggest is updating to version 1.9.0 of the toolkit. 

Here is a sample of my output, proving that the toolkit it functioning as expected. I am using v1.9.0
<img width="284" alt="image" src="https://user-images.githubusercontent.com/58299919/160376372-bb333705-c482-4a61-a2df-0b7ed2a7edbe.png">

If this does not resolve it, you may have a permissions issue. Please double check that the user you are using has all required permissions, particularly CloudHub Network Viewer and Organisation Admin. 

Thanks

**Comment by MartijnvdB** [comment]
Hi,

Thanks for the quick reply. 

For security reasons we want to keep the permissions for the system account that we use to a minimum. Hence we do not want to give the account 'Organization Administrator' and 'CloudHub Admin' roles (any engineer with access to the password management tool would be able to become Admin on the platform). These _are_ mentioned as prerequisites.

So basically the account only has _View_ and _Read_ permissions.

How likely is it that the issue is caused by a lack of permissions?

**Comment by richardmckinley** [comment]
Hi @MartijnvdB 

I understand the security concern but these are limitations and requirements of the platform APIs used by the toolkit. This is certainly the cause of your issue. 

Purely from a security perspective, you may want to consider using a connected app. However, there are limitations on which metrics are available using a connected app, but it seems like these are limits you are already enforcing but not providing the full scope of permissions to the user account. Please see the Limitations section of the docs for a list of metrics which are not available if using a connected app. 

Thanks

**Comment by MartijnvdB** [comment]
Hi @richardmckinley,

Please go ahead and close this request. For now we will live with the existing limitations (of Anypoint, and of our security guidelines).

Best regards,

Martijn
