### ISSUE TITLE
 CH API clients show 0

### ISSUE THREAD

**Issue by MartijnvdB** [mulesoft-catalyst/metrics-toolkit#183]
In metrics-toolkit v1.8.2 with CloudHub, the 'API Client Applications - Current Count' metric in the 'MC - Access Management Metrics' dashboard always shows 0, even though all our APIs use the 'client ID enforcement' policy, and thus have clients.

![hc_1030](https://user-images.githubusercontent.com/16452270/160373708-357d3105-68a5-45de-9f3d-a18dee806326.png)

It seems that the relevant Anypoint API call that is used for this metric is **https://anypoint.mulesoft.com/apiplatform/repository/v2/organizations/:orgId/applications**. However, when I run that in Postman it does not return any useful data for both of our organization IDs:

![image](https://user-images.githubusercontent.com/16452270/160374047-ba5fbaf0-4d98-40cc-bb28-1338b75cf65a.png)

Note that the above resource is **v2** - perhaps MuleSoft changed something in the output of this API since **v1**, and the data that is expected is in a different location?

We are using an Anypoint account, not a connected app, to access the Anypoint APIs.

**Comment by richardmckinley** [comment]
Hi @MartijnvdB 

As with the other issue you raised, please update to v1.9.0 as a first step. Similarly, I would double check permissions provided to the user as you can see below the toolkit working as expected when I send a request to Get metrics.
<img width="208" alt="image" src="https://user-images.githubusercontent.com/58299919/160378114-0ea4c790-2b69-453f-8e6d-facc1b624e27.png">
