### ISSUE TITLE
Splunk Dashboards Invalid Metrics

### ISSUE THREAD

**Issue by paclife** [mulesoft-catalyst/metrics-toolkit#41]
Many of the Splunk dashboards are using the `stats max(total)` for calculations, however these numbers are not true representations when aggregating across multiple business groups.  To get total across all business groups we've had to manually change the queries to use `stats sum(total)`

**Comment by olamiral-mulesoft** [comment]
Hi!

Thank you for posting your issue. 

As you've already adjusted the dashboards, would you mind to share your version of the modified dashboards so we can analyse and fix them accordingly?

Thank you!

**Comment by panizzag** [comment]
Hi @paclife 
Just doing a follow-up on this. Have you had the chance to look at the comment posted by Olivier?

Thanks,
Gaston

**Comment by richardmckinley** [comment]
Hi @paclife,
I am going to mark this issue as closed for now. If you would like to re-open it please leave a new comment and tag me in your response. 
Thanks and regards, 
Richard
