### ISSUE TITLE
Integration into Salesforce Dashboards (and/or Einstein) for joint customers

### ISSUE THREAD

**Issue by simonvicary** [mulesoft-catalyst/metrics-toolkit#62]
I've also raised on internal discussions regards connecting the M-A into any kind of dashboard features available within Salesforce (or even using Einstein Analytics etc.) if that's possible.  Even better, some kind of OOTB connector within M-A into SF's APIs and some pre-built dashboards to get going.

**Background:**
A couple of existing customers have SF already so have asked if they could display KPI or Metrics data from the platform (M-A) in the SF platform - given we're part of the same company, I think it would be a great offering to go hand-in-hand with the M-A component, which provides joint customers an out of the box dashboard capability.  

If customer already have SF in their landscape; I believe there is a suitable API to Einstein in SF - from what I understand it's made for processing data from external sources.  I don't know enough about the dashboarding capabilities in SF though - so only going from customer requests - but if it can be used to store historical data/trends - even better.

It'll require close collaboration with SF teams to utilise full capabilities of both platforms to see how they can complement each-other and see if the dashboard capabilities could accelerate our customers wanting KPI Dashboards to measure platform benefits over time.

**Comment by simonvicary** [comment]
Using the CSV Output from the existing tool, I have written a small app (which I will incorporate as a built-in capability) into the MA tool - to inject the metrics into SF Einstein Analytics.  Thes setting up of dashboards is a set of manual steps, but anything which can be exported for quick setup, I will add to the project as a set of basic pre-built EA Dashboards.  This will be the first set of EA capabilities and will undoubtedly enhance over time.  I'll start to develop a loader on a separate branch and ensure it's working and aligned before moving forward - it will basically piggy-back of of the CSV Loader (as it is easier to be CSV format in order to upload to Einstein Analytics)

**Comment by damiancalabresi** [comment]
Thanks Simon, I'm not aware of the EA capabilities and API, but feel free to implement the loader on a branch, make a pull request, and ask for help in any case.

**Comment by olamiral-mulesoft** [comment]
@simonvicary wrote this article: https://wiki.corp.mulesoft.com/display/PSE/Metrics+and+KPIs+solutions
We should see how we can incorporate the content of this article to Metrics Accelerator documentation.
Also, we need to define how we're going to incorporate the EA strategy.
