### ISSUE TITLE
Source code for web view

### ISSUE THREAD

**Issue by jdiffenthal** [mulesoft-catalyst/metrics-toolkit#88]
Hi Guys

Would it be possible to get the unminified angular source code checked in for the ApiManager?
The service is returning the data will want to make the UX more granualar.

Thanks in advance!

**Comment by panizzag** [comment]
Hi @jdiffenthal 
Thanks for your question. What do you mean with angular source code checked in for API Manager? Do you need the Embedded Dashboard source?

Thanks,
Gaston

**Comment by richardmckinley** [comment]
Hi @jdiffenthal,
I am going to mark this issue as closed for now. If you would like to re-open it please leave a new comment and tag me in your response. 
Thanks and regards, 
Richard
