### ISSUE TITLE
Limitations when authenticating with Connected Apps

### ISSUE THREAD

**Issue by zmsd25** [mulesoft-catalyst/metrics-toolkit#94]
Since there is a limitation when connecting using Connected Apps, for organisations using SSO to login to Anypoint platform what would be the preferred mode of authentication ?

**Comment by panizzag** [comment]
Hi @zmsd25 ,
The preferred mode would be Connected Apps. What kind of limitation are you referring to?

Regards,
Gaston

**Comment by richardmckinley** [comment]
Hi @zmsd25, 
I am going to mark this issue as closed for now. If you would like to re-open it please leave a new comment and tag me in your response. 
Thanks and regards, 
Richard
